name: 'sqlserver'
version: 0.0.1

config-version: 2

# profile needs to be in  ~/.dbt/profiles.yml file
profile: 'dbt-sqlserver'

macro-paths: ["macros"]
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]
